import type { SoundProfile, SoundProfileId } from "./profileTypes";

export const builtInProfiles: Record<SoundProfileId, SoundProfile> = {
  // Tiny Scooter = buzzy tiny engine: small saw/pulse body, light noise, no siren wobble.
  "tiny-scooter": {
    id: "tiny-scooter",
    engineType: "synthetic",
    name: "Tiny Scooter",
    description: "Small buzzy moped energy without UFO wobble.",
    waveform: "sawtooth",
    subWaveform: "square",
    baseFrequency: 118,
    pitchRange: 260,
    filterBase: 720,
    filterRange: 2600,
    gainScale: 0.9,
    burstIntensity: 0.85,
  },
  // Sport Exhaust = synthetic exhaust growl: lower body, stronger sub, mild saturation.
  "sport-exhaust": {
    id: "sport-exhaust",
    engineType: "synthetic",
    name: "Sport Exhaust",
    description: "Deeper synthetic growl with a stronger vroom.",
    waveform: "sawtooth",
    subWaveform: "square",
    baseFrequency: 48,
    pitchRange: 270,
    filterBase: 260,
    filterRange: 3000,
    gainScale: 0.95,
    burstIntensity: 1.15,
  },
  // Jet Fan = smooth turbine/fan: filtered noise leads, oscillator is only a low bed.
  "jet-fan": {
    id: "jet-fan",
    engineType: "synthetic",
    name: "Jet Fan",
    description: "Smooth fan ramp with a soft turbine wash.",
    waveform: "triangle",
    subWaveform: "sine",
    baseFrequency: 72,
    pitchRange: 150,
    filterBase: 520,
    filterRange: 5200,
    gainScale: 0.86,
    burstIntensity: 0.42,
  },
  "safe-demo-engine": {
    id: "safe-demo-engine",
    engineType: "sampleHybrid",
    name: "Safe Demo Engine",
    displayName: "Safe Demo Engine",
    description: "Sample-hybrid demo pack scaffold. No audio files are bundled yet.",
    author: "CPUpovic contributors",
    license: "No audio assets bundled",
    sourceUrl: "",
    assets: {
      idle: "idle.wav",
      low: "low.wav",
      mid: "mid.wav",
      high: "high.wav",
      revBurst: "rev_burst.wav",
      cooldown: "cooldown.wav",
    },
    tuning: {
      crossfadeMs: 180,
      minPlaybackRate: 0.95,
      maxPlaybackRate: 1.08,
      idleGain: 0.45,
      lowGain: 0.58,
      midGain: 0.74,
      highGain: 0.9,
      oneShotGain: 0.72,
      effectCooldownMs: 900,
    },
  },
  "local-engine": {
    id: "local-engine",
    engineType: "sampleHybrid",
    name: "Local Engine Pack",
    displayName: "Local Engine Pack",
    description: "User-provided local sample-hybrid pack. Add legal idle/low/mid/high loops.",
    author: "Local user",
    license: "Audio asset terms documented separately in LICENSES.md",
    sourceUrl: "",
    assets: {
      idle: "idle.wav",
      low: "low.wav",
      mid: "mid.wav",
      high: "high.wav",
      revBurst: "rev_burst.wav",
      cooldown: "cooldown.wav",
    },
    tuning: {
      crossfadeMs: 180,
      minPlaybackRate: 0.96,
      maxPlaybackRate: 1.06,
      idleGain: 0.4,
      lowGain: 0.56,
      midGain: 0.68,
      highGain: 0.78,
      oneShotGain: 0.68,
      effectCooldownMs: 900,
    },
  },
  supara: {
    id: "supara",
    engineType: "sampleHybrid",
    name: "Supara Pack",
    displayName: "Supara Pack",
    description:
      "Fictional turbo tuner-style engine soundpack with boost, flutter, burble, and limiter effects.",
    author: "etherman-os",
    license: "Adobe Firefly generated output",
    sourceUrl: "",
    assets: {
      idle: "idle.wav",
      low: "low.wav",
      mid: "mid.wav",
      high: "high.wav",
      revBurst: "rev_burst.wav",
      cooldown: "cooldown.wav",
      antiLagPops: "anti_lag_pops.wav",
      boostSpool: "boost_spool.wav",
      burbleShort: "burble_short.wav",
      redlineBurst: "redline_burst.wav",
      revLimiter: "rev_limiter.wav",
      turboFlutter: "turbo_flutter.wav",
    },
    tuning: {
      crossfadeMs: 170,
      minPlaybackRate: 0.96,
      maxPlaybackRate: 1.06,
      idleGain: 0.42,
      lowGain: 0.58,
      midGain: 0.72,
      highGain: 0.86,
      oneShotGain: 0.75,
      effectCooldownMs: 900,
    },
  },
};

export const builtInProfileList: SoundProfile[] = [
  builtInProfiles["local-engine"],
  builtInProfiles.supara,
  builtInProfiles["sport-exhaust"],
  builtInProfiles["tiny-scooter"],
  builtInProfiles["jet-fan"],
];

export function isSoundProfileId(value: unknown): value is SoundProfileId {
  return typeof value === "string" && Object.prototype.hasOwnProperty.call(builtInProfiles, value);
}
